In [2]:
import numpy as np
a = np.array([12, 132, 161, 184, 682, 666, 42069])
a

array([   12,   132,   161,   184,   682,   666, 42069])

In [3]:
b = np.array([[1, 2, 7], [3, 4, 5]])
b

array([[1, 2, 7],
       [3, 4, 5]])

In [4]:
m = np.array([[13, 25, 5.71, 9.3], [92, 32, 4.56, 1]])
m

array([[13.  , 25.  ,  5.71,  9.3 ],
       [92.  , 32.  ,  4.56,  1.  ]])

In [5]:
m.shape

(2, 4)

In [6]:
type(m)

numpy.ndarray

In [7]:
m.dtype

dtype('float64')

In [8]:
z = np.zeros(5) #массив из нулей
z

array([0., 0., 0., 0., 0.])

In [9]:
o = np.ones((3, 8)) #двумерный массив из единиц, размером 3 на 8
o

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
r = np.arange(0, 30, 2) #массив от 0 до 30 с шагом 2
r

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [11]:
e = np.eye(5) #единичная матрица размером 5 на 5
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
em = np.empty((2, 5))
em

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261095e-306, 6.23061763e-307],
       [2.22526399e-307, 6.23053614e-307, 7.56592338e-307,
        9.34588061e-307, 2.78134236e-309]])

In [13]:
test_ar = np.arange(0, 100, 10)
test_ar

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
#по отдельности выводим первый эл массива, последний и седьмой
print(test_ar[0]) 
print(test_ar[-1])
print(test_ar[6])

0
90
60


In [15]:
print(test_ar[2:6]) #со второго по пятый эл
print(test_ar[::2]) # каждый второй эл
print(test_ar[3:]) # с третьего эл и до конца
print(test_ar[:2]) #с начала и до первого эл 

[20 30 40 50]
[ 0 20 40 60 80]
[30 40 50 60 70 80 90]
[ 0 10]


In [16]:
t1 = np.array([1, 2, 4, 6, 7])
t1

array([1, 2, 4, 6, 7])

In [17]:
t2 = np.arange(0, 10, 2)
t2

array([0, 2, 4, 6, 8])

In [18]:
s = t1+t2
s

array([ 1,  4,  8, 12, 15])

In [19]:
d = t1-t2
d

array([ 1,  0,  0,  0, -1])

In [20]:
m = t1*t2
m

array([ 0,  4, 16, 36, 56])

In [21]:
p = t1**t2
p

array([      1,       4,     256,   46656, 5764801])

In [22]:
print(t1*2)
print(t2+11)

[ 2  4  8 12 14]
[11 13 15 17 19]


In [23]:
print(np.sqrt(t1))
print(np.exp(t2))

[1.         1.41421356 2.         2.44948974 2.64575131]
[1.00000000e+00 7.38905610e+00 5.45981500e+01 4.03428793e+02
 2.98095799e+03]


In [24]:
a = np.array([3, 7, 15, 24, 42, 117, 22, 4, 5, 65, 73, 82])
a

array([  3,   7,  15,  24,  42, 117,  22,   4,   5,  65,  73,  82])

In [25]:
print(np.mean(a)) #среднее
print(np.median(a)) #медиана
print(np.std(a)) #стандартное отклонение
print(np.var(a)) #дисперсия
print(np.min(a)) #минимальное
print(np.max(a)) #максимальное
print(np.sum(a)) #сумма

38.25
23.0
36.00723306966717
1296.5208333333333
3
117
459


In [26]:
b = np.array([[1, 2], [3, 4], [5, 6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
print(np.mean(b))
print(np.mean(b, axis = 1)) #среднее по строкам
print(np.mean(b, axis = 0)) #среднее по столбцам

3.5
[1.5 3.5 5.5]
[3. 4.]
